site_name: Dev Guidelines (GitFlow / GitLab)
site_description: Внутренняя документация по процессам разработки, ветвления и релизам
site_url: https://example.com/dev-guidelines
repo_url: https://gitlab.example.com/group/dev-guidelines
repo_name: dev-guidelines
copyright:
  '© Company Name'

docs_dir: docs

nav:
  - Главная: README.md
  - 01. Назначение документа: 01_intro.md
  - 02. Роли и ответственность: 02_roles-and-responsibilities.md
  - 03. Процесс работы с ветками: 03_branching-guidelines.md
  - 04. Подготовка релиза: 04_release-preparation.md
  - 05. Процесс Hotfix: 05_hotfix-process.md
  - 06. Защищённые ветки: 06_protected-branches.md
  - 07. Контроль нарушений и аудит: 07_audit-and-compliance.md
  - 08. Интеграция с CI/CD: 08_ci-cd-integration.md
  - 09. Контроль и актуализация: 09_ci-cd-integration.md

theme:
  name: material
  language: ru
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
