site_name: Dev Guidelines (GitFlow / GitLab)
site_description: Внутренняя документация по процессам разработки, ветвления и релизам
site_url: https://example.com/dev-guidelines
repo_url: https://gitlab.example.com/group/dev-guidelines
repo_name: dev-guidelines
copyright:
  '© Company Name'

docs_dir: docs

nav:
  - Главная: README.md
  - 01. Назначение документа: 01_intro.md
  - 02. Роли и ответственность: 02_roles-and-responsibilities.md
  - 03. Структура ветвления (GitFlow): 03_branching-structure.md
  - 04. Процесс работы с ветками: 04_branching-guidelines.md
  - 05. Подготовка релиза: 05_release-preparation.md
  - 06. Процесс Hotfix: 06_hotfix-process.md
  - 07. Защищённые ветки: 07_protected-branches.md
  - 08. Контроль нарушений и аудит: 08_audit-and-compliance.md
  - 09. Интеграция с CI/CD: 09_ci-cd-integration.md
  - 10. Контроль и актуализация: 10_review-and-updates.md

theme:
  name: material
  language: ru
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
